openapi: 3.0.0
info:
  description: "API endpoint to make using Leetcode's API a bit easier."
  version: 1.0.0
  title: Leetcode API
servers:
  - url: http://140.238.151.56/leetcode/
    description: OCI instance
tags:
  - name: meta
    description: Endpoints about the API
paths:
  /user:
    post:
      description: Fetchs all data for given user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
              properties:
                username:
                  type: string
                  example: leetcode
      responses:
        "200":
          description: All data for a user
          content:
            application/json: {}
    get:
      description: Fetchs all data for given user
      parameters:
        - in: query
          name: username
          schema:
            type: string
            example: leetcode
          required: true
          description: Username to fetch
      responses:
        "200":
          description: All data for a user 
          content:
            application/json: {}
  /health-check:
    get:
      tags:
        - meta
      description: ""
      responses:
        "200":
          description: Health check for API
          content:
            text/plain:
              schema:
                type: string
                enum:
                  - alive
  /usage:
    post:
      tags:
        - meta
      description: "API usage instructions"
      responses:
        "200":
          description: API usage instructions
          content:
            application/yaml: {}
